### PR TITLE
new option

### PR DESCRIPTION
**Pull request by rtrieu**
### What does this PR do?

Describes a new config set up option for automatically collecting user data.

### Motivation

[DOCS-4882](https://datadoghq.atlassian.net/browse/DOCS-4882), which is a part of [DOCS-4827](https://datadoghq.atlassian.net/browse/DOCS-4827).

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)
- [ ] If this PR is auto-generated, please make sure also to manually update the code related to the change

[DOCS-4882]: https://datadoghq.atlassian.net/browse/DOCS-4882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-4827]: https://datadoghq.atlassian.net/browse/DOCS-4827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by louiszawadzki — APPROVED** [review]
This looks good to me, could you maybe include the `new-rum-app-react.png` image to see what it looks like?

**Comment by rtrieu** [comment]
@louiszawadzki Just added. Let me know if it should be moved somewhere else!

**Review by buraizu — APPROVED** [review]
LGTM

**Comment by louiszawadzki** [comment]
Sorry, there was no need to add it in the code, just a screenshot in the comment would have been enough :) 
If the image is not sourced from here, you can remove it and merge :)

**Review by xgouchet — APPROVED** [review]

**Pull request merged**
